/**
 * GravityWorker Initial Migration
 *
 * @module gravity-worker/migrations/0001_init
 */

// Placeholder for initial migration
// Migrations will be auto-generated by makemigrations
export const migration = {
  name: "0001_init",
  app: "gravity-worker",
  operations: [],
};
